try:
    number = int(input("entrer a num: "))
    print("THE nuber enered is", number)
exept ValueError as ex:
    print("exeption:" ex)